# Generated by Django 4.2.4 on 2023-08-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_certificate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='degre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
