# Generated by Django 4.2.4 on 2023-08-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_certificate_date_certificate_degre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='degre',
        ),
    ]
